# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: corne36w_left
  - board: nice_nano_v2
    shield: corne36w_right
  - board: piantor_pro_bt_left/nrf52840
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: piantor_pro_bt_left-nice_view-zmk
  - board: piantor_pro_bt_right/nrf52840
    shield: nice_view
    snippet: studio-rpc-usb-uart
    artifact-name: piantor_pro_bt_right-nice_view-zmk
  - board: piantor_pro_bt_left/nrf52840
    shield: settings_reset
    snippet: studio-rpc-usb-uart
    artifact-name: piantor_pro_bt_left-settings_reset-zmk
  - board: piantor_pro_bt_right/nrf52840
    shield: settings_reset
    snippet: studio-rpc-usb-uart
    artifact-name: piantor_pro_bt_right-settings_reset-zmk
